# Generated by Django 2.2.5 on 2019-10-22 01:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GradeManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentgrade',
            name='Assignment',
        ),
        migrations.AddField(
            model_name='assignmentgrade',
            name='Assignment',
            field=models.ManyToManyField(to='GradeManagement.Assignment'),
        ),
        migrations.AlterField(
            model_name='assignmentgrade',
            name='GradeOfAssignment',
            field=models.IntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='assignmentgrade',
            name='UserOfAssignment',
        ),
        migrations.AddField(
            model_name='assignmentgrade',
            name='UserOfAssignment',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grade', models.IntegerField(null=True)),
                ('Course', models.ManyToManyField(to='GradeManagement.Course')),
                ('Students', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
