# Generated by Django 2.2.5 on 2019-11-04 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GradeManagement', '0002_auto_20191021_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='Course',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='Course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GradeManagement.Course'),
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='Students',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='Students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
