# Generated by Django 2.2.5 on 2019-11-04 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GradeManagement', '0003_auto_20191103_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentgrade',
            name='Assignment',
        ),
        migrations.AddField(
            model_name='assignmentgrade',
            name='Assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GradeManagement.Assignment'),
        ),
        migrations.RemoveField(
            model_name='assignmentgrade',
            name='UserOfAssignment',
        ),
        migrations.AddField(
            model_name='assignmentgrade',
            name='UserOfAssignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
