# Generated by Django 2.2.5 on 2019-11-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradeManagement', '0004_auto_20191103_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='Active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Grade',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
